name: stifmaps-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - scikit-image
  - opencv
  - pytorch
  - torchvision
  - pip:
      - STIFMaps  # or the name of your pip-distributed package
